### ISSUE TITLE
not build 

### ISSUE THREAD

**Issue by selevo** [adrielcafe/ChromaAndroidApp#1]

**Comment by selevo** [comment]
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\src\nullnull\debug\google-services.json
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\src\debug\nullnull\google-services.json
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\src\nullnull\google-services.json
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\src\debug\google-services.json
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\src\nullnullDebug\google-services.json
E:\Kladovka\Android\Projects\ChromaAndroidApp-master\ChromaAndroidApp-master\app\google-services.json

**Comment by adrielcafe** [comment]
Hi @selevo ,

To build this project for yourself you have two options:
1. Create a [Firebase project](https://firebase.google.com/docs/android/setup), download the `google-services.json` and replace the local file

2. Remove the firebase plugin on `build.gradle` and the firebase and crashlytics dependencies on `app/build.gradle`

I hope this help. Feel free to reopen this issue if you have more questions.
